OfficeSite/Models/Job.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_infoGlobalNew.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class Job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job()
        {
            this.Apply = new HashSet<Apply>();
        }
    
        public int Id { get; set; }
        public string JobType { get; set; }
        [AllowHtml]
        public string Description { get; set; }
        public string Status { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public string Position { get; set; }
        public string EmploymentType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apply> Apply { get; set; }
    }
}

OfficeSite/Controllers/JobsController.cs
using E_infoGlobalNew.Models;
using Google.Apis.Drive.v3.Data;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static E_infoGlobalNew.Helper.ApplicationHelper;

namespace E_infoGlobalNew.Controllers
{
    public class JobsController : Controller
    {
        private InfoEntities dbContext = new InfoEntities();
        public ActionResult Index()
        {
            ViewBag.Records = dbContext.Jobs.ToList();
            return View();
        }
        public ActionResult Add()
        {
            ViewBag.PageType = EnumPageType.Add;
            return View("Form", new Job());
        }
        [HttpGet]
        public JsonResult GetRecord(int Id)
        {
            var Records = dbContext.Jobs.FirstOrDefault(x => x.Id == Id);
            return Json(Records, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public ActionResult Edit(int Id)
        {
            var Records = dbContext.Jobs.FirstOrDefault(x => x.Id == Id);
            return View("Form", Records);
        }
        [HttpPost]
        public ActionResult Save(Job modelRecords) 
        {
            if (modelRecords != null)
            {

                if (modelRecords.Id == 0)
                {
                    modelRecords.CreatedBy = 1;
                    modelRecords.CreatedDateTime = DateTime.Now;
                    dbContext.Jobs.Add(modelRecords);
                }
                else
                {
                    modelRecords.UpdateBy = 1;
                    modelRecords.UpdateDateTime = DateTime.Now;
                    modelRecords.CreatedDateTime = DateTime.Now;
                    dbContext.Entry(modelRecords).State = EntityState.Modified;
                }
                dbContext.SaveChanges();
            }
            TempData["Edit"] = "Record Successfully";
            return RedirectToAction("Index");
        }
    }
}

OfficeSite/Views/Jobs/Form.cshtml
@model E_infoGlobalNew.Models.Job

@{
    ViewBag.Title = "Form";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}
<link rel="stylesheet" href="https://cdn.ckeditor.com/ckeditor5/46.0.2/ckeditor5.css">
<div class="row">
    <div class="col-md-12">
        <div class="card mb-4">
            <div class="card-body">
                @using (Html.BeginForm("Save", "Jobs", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    <div class="row">
                        <div class="col-md-4 form-group mb-3">
                            <label for="Name">Name</label>
                            <input type="text" name="JobType" id="nm" class="form-control">
                            <input type="hidden" name="Id"  id="d" class="form-control">
                            <input type="hidden" name="CreatedBy"  id="create" class="form-control">
                            <input type="hidden" name="CreatedDateTime"  id="datetime" class="form-control">
                        </div>
                        <div class="col-md-4 form-group mb-3">
                            <label for="Position">Position</label>
                            <input type="text" name="Position"  id="pos" class="form-control">
                        </div>
                        <div class="col-md-4 form-group mb-3">
                            <label for="EmploymentType">Employment Type</label>
                            <input type="text" name="EmploymentType"  id="type" class="form-control">
                        </div>
                        <div class="col-md-12 form-group mb-3">
                            <label for="Description">Description</label>
                            <textarea class="form-control" name="Description" id="desc"></textarea>
                        </div>
                        <div class="col-md-4 form-group mb-3">
                            <label for="Sta">Select</label>
                            <select name="Status"  id="st" class="form-control">
                                <option>Enable</option>
                                <option>Disable</option>
                            </select>
                        </div>

                        <div class="col-md-12">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
<script src="https://cdn.ckeditor.com/4.22.1/standard/ckeditor.js"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    debugger
    CKEDITOR.replace('desc');
    //const url = window.location.pathname; // e.g., /page/1
    //const segments = url.split('/').filter(Boolean); // removes empty strings
    //const Id = segments.length ? segments[segments.length - 1] : null;
    const pathSegments = window.location.pathname.split('/').filter(Boolean);
    const Id = pathSegments[pathSegments.length - 1];
    console.log(Id);
    getUserById(Id);
    function getUserById(Id) {
        debugger
        $.ajax({
            url: '/Jobs/GetRecord',
            type: 'GET',
            data: { Id: Id },
            success: function (Records) {

                console.log(Records);
                $('#create').val(Records.CreatedBy);
                $('#datetime').val(Records.CreatedDateTime);
                $('#pos').val(Records.Position);
                $('#d').val(Records.Id);
                $('#nm').val(Records.JobType);
                $('#type').val(Records.EmploymentType);
                $('#st').val(Records.Status);
                $('#desc').val(Records.Description);
            },
            error: function (xhr, status, error) {
                console.error("Error:", error);
            }
        });
    }

    // Example usage
    
</script>

OfficeSite/Views/Jobs/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<div class="col-md-12 mb-3">
    <div class="card text-left">
        <div class="dataTablePageHeader card-header">
            <a href="jobs/add" class="btn btn-primary pull-right">Add <i class="fa fa-plus"></i></a>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th scope="col">Id</th>
                            <th scope="col">Name</th>
                            <th scope="col">Postion</th>
                            <th scope="col">Employment Type</th>
                            <th scope="col">Status</th>
                            <th scope="col">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (ViewBag.Records != null)
                        {
                            foreach (var Records in ViewBag.Records)
                            {
                                <tr>
                                    <td>@Records.Id</td>
                                    <td>@Records.JobType</td>
                                    <td>@Records.Position</td>
                                    <td>@Records.EmploymentType</td>
                                    <td>@Records.Status</td>
                                    <td>
                                        @Html.ActionLink(" ","Edit", new { Id = Records.Id }, new { @class = "btn btn-success btn-sm nav-icon i-Pen-2 font-weight-bold" })
                                        @*<a href="/edit?Id=@Records.Id" class="btn btn-success btn-sm">
                                            <i class="nav-icon i-Pen-2 font-weight-bold"></i>
                                        </a>*@
                                        @*<a href="#" class="text-danger mr-2">
            <i class="nav-icon i-Close-Window font-weight-bold"></i>
        </a>*@
                                    </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>


        </div>
    </div>
</div>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
@if (TempData["Edit"] != null)
{
    <script>
        debugger
        swal("Thank You", "@TempData["Edit"]", "success");
    </script>
}